# Generated by Django 4.2.5 on 2024-02-24 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerdashboard', '0003_alter_productinfo_seller_id'),
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featuredproducts', to='sellerdashboard.productinfo'),
        ),
    ]
