# Generated by Django 4.2.5 on 2023-11-08 08:53

from django.db import migrations, models
import django.db.models.deletion
import sellerdashboard.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admindashboard', '0002_remove_partinfo_sellingprice_and_more'),
        ('profileseller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellingPrice', models.CharField()),
                ('stockQuantity', models.CharField()),
                ('units', models.CharField()),
                ('part_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Part', to='admindashboard.partinfo')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='profileseller.seller')),
            ],
        ),
        migrations.CreateModel(
            name='producttags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='sellerdashboard.productinfo')),
            ],
        ),
        migrations.CreateModel(
            name='productimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=sellerdashboard.models.unique_filename)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sellerdashboard.productinfo')),
            ],
        ),
    ]
