# Generated by Django 4.2.5 on 2024-02-15 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileseller', '0003_seller_seller'),
        ('sellerdashboard', '0002_productinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='profileseller.seller'),
        ),
    ]
