# Generated by Django 4.2.5 on 2024-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerdashboard', '0003_alter_productinfo_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='sellingPrice',
            new_name='normalRate',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='bulkRate',
            field=models.CharField(blank=True, null=True),
        ),
    ]
