# Generated by Django 4.2.5 on 2024-03-18 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('total_items', models.PositiveIntegerField()),
                ('total_price', models.FloatField()),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cart')),
            ],
        ),
    ]
