# Generated by Django 4.2.5 on 2024-04-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
