# Generated by Django 4.2.5 on 2024-04-14 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerdashboard', '0007_alter_producttags_unique_together'),
        ('users', '0007_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product_id',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sellerdashboard.productinfo'),
            preserve_default=False,
        ),
    ]
