# Generated by Django 4.2.5 on 2024-04-18 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_remove_review_product_id_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('descriptiveaddress', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.address'),
            preserve_default=False,
        ),
    ]
