# Generated by Django 4.2.5 on 2023-11-07 06:15

import admindashboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='partinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleCompany', models.CharField()),
                ('subCategory', models.CharField()),
                ('brand', models.CharField()),
                ('model', models.CharField()),
                ('manufactureYear', models.CharField()),
                ('partCategories', models.CharField(blank=True, null=True)),
                ('partSubCategories', models.CharField()),
                ('partNumber', models.CharField()),
                ('partName', models.CharField()),
                ('stockQuantity', models.CharField()),
                ('sellingPrice', models.CharField()),
                ('units', models.CharField()),
                ('description', models.TextField(blank=True, null=True)),
                ('availability', models.CharField()),
                ('image', models.ImageField(blank=True, upload_to=admindashboard.models.unique_filename)),
                ('status', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='partimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=admindashboard.models.unique_filename)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='admindashboard.partinfo')),
            ],
        ),
        migrations.CreateModel(
            name='partAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributeName', models.CharField(blank=True, null=True)),
                ('attributeValue', models.CharField(blank=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='admindashboard.partinfo')),
            ],
        ),
    ]
