# Generated by Django 4.2.5 on 2023-11-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partinfo',
            name='sellingPrice',
        ),
        migrations.RemoveField(
            model_name='partinfo',
            name='stockQuantity',
        ),
        migrations.RemoveField(
            model_name='partinfo',
            name='units',
        ),
    ]
