# Generated by Django 4.2.5 on 2023-12-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0003_vechilebrand_vechilecompany_remove_partinfo_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partinfo',
            name='availability',
        ),
        migrations.AddField(
            model_name='partinfo',
            name='vechileBrand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='admindashboard.vechilebrand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partinfo',
            name='vechileCompany',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='admindashboard.vechilecompany'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partinfo',
            name='vechileModel',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='model', to='admindashboard.vechilemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partinfo',
            name='partCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='admindashboard.partcategory'),
        ),
    ]
