# Generated by Django 4.2.5 on 2023-12-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0004_remove_partinfo_availability_partinfo_vechilebrand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partcategory',
            name='vechileModel',
        ),
    ]
