# Generated by Django 4.2.5 on 2024-01-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0005_remove_partcategory_vechilemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vechilebrand',
            name='vechileCompany',
        ),
        migrations.RemoveField(
            model_name='vechilemodel',
            name='vechileBrand',
        ),
        migrations.RemoveField(
            model_name='partinfo',
            name='partCategory',
        ),
        migrations.RemoveField(
            model_name='partinfo',
            name='vechileBrand',
        ),
        migrations.RemoveField(
            model_name='partinfo',
            name='vechileCompany',
        ),
        migrations.RemoveField(
            model_name='partinfo',
            name='vechileModel',
        ),
        migrations.AddField(
            model_name='partinfo',
            name='availability',
            field=models.CharField(default='NULL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partinfo',
            name='brand',
            field=models.CharField(default='BRAND'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partinfo',
            name='manufactureYear',
            field=models.CharField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partinfo',
            name='model',
            field=models.CharField(default='Model'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partinfo',
            name='partCategories',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partinfo',
            name='subCategory',
            field=models.CharField(default='SUB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partinfo',
            name='vehicleCompany',
            field=models.CharField(default='COMPANY'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='partCategory',
        ),
        migrations.DeleteModel(
            name='vechileBrand',
        ),
        migrations.DeleteModel(
            name='vechileCompany',
        ),
        migrations.DeleteModel(
            name='vechileModel',
        ),
    ]
