# Generated by Django 4.2.5 on 2024-01-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0006_remove_vechilebrand_vechilecompany_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partinfo',
            name='availability',
            field=models.CharField(default='In Stock'),
        ),
    ]
