# Generated by Django 4.2.5 on 2024-03-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileseller', '0007_alter_sellerprofile_storelogo_and_more'),
        ('admindashboard', '0009_alter_partnumber_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_provided', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('credit_added', models.DateTimeField(blank=True, null=True)),
                ('balance_updated', models.DateTimeField(blank=True, null=True)),
                ('credit_used', models.DateTimeField(blank=True, null=True)),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to='profileseller.seller')),
            ],
        ),
    ]
