# Generated by Django 4.2.5 on 2024-03-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0010_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='partimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/partimages/')),
            ],
        ),
    ]
