# Generated by Django 4.2.5 on 2024-04-20 05:38

import admindashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0011_partimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=admindashboard.models.unique_filename),
        ),
    ]
