# Generated by Django 4.2.5 on 2023-12-12 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashboard', '0002_remove_partinfo_sellingprice_and_more'),
        ('quotation', '0002_unidentifiedproduct_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='specificsellerquotation',
            name='product_id',
        ),
        migrations.AddField(
            model_name='quotation',
            name='part_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.partinfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specificsellerquotation',
            name='part_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admindashboard.partinfo'),
            preserve_default=False,
        ),
    ]
