# Generated by Django 4.2.5 on 2023-12-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_rename_quoted_price_specificsellerquotation_quoted_per_per_unit_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
