# Generated by Django 4.2.5 on 2023-12-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_remove_specificsellerquotation_part_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificsellerquotation',
            old_name='quoted_per_per_unit_total',
            new_name='quoted_total_price',
        ),
    ]
