# Generated by Django 4.2.5 on 2023-12-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_rename_quoted_per_per_unit_total_specificsellerquotation_quoted_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificsellerquotation',
            old_name='quoted_total_price',
            new_name='quoted_price_total',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='product_info',
        ),
        migrations.RemoveField(
            model_name='specificsellerquotation',
            name='order_id',
        ),
        migrations.AddField(
            model_name='specificsellerquotation',
            name='quotation_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quotation.quotation'),
            preserve_default=False,
        ),
    ]
