# Generated by Django 4.2.5 on 2023-12-14 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellerdashboard', '0002_productinfo_status'),
        ('quotation', '0009_rename_quoted_total_price_specificsellerquotation_quoted_price_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='product_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sellerdashboard.productinfo'),
            preserve_default=False,
        ),
    ]
