# Generated by Django 4.2.5 on 2023-12-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0010_quotation_product_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='product_info',
        ),
    ]
