# Generated by Django 4.2.5 on 2023-12-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_remove_quotation_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specificsellerquotation',
            name='quoted_price_per_unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specificsellerquotation',
            name='quoted_price_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
