# Generated by Django 4.2.5 on 2024-03-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0013_unidentifiedproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remaining_balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
