# Generated by Django 4.2.5 on 2023-11-07 06:15

from django.db import migrations, models
import django.db.models.deletion
import profileseller.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField()),
                ('province', models.CharField()),
                ('area', models.CharField()),
                ('district', models.CharField()),
                ('additionalphone', models.CharField()),
                ('descriptiveaddress', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField()),
                ('businessregdnumber', models.CharField()),
                ('businessdocument', models.ImageField(upload_to=profileseller.models.unique_filename)),
                ('bankdocument', models.ImageField(upload_to=profileseller.models.unique_filename)),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storename', models.CharField()),
                ('storeemail', models.EmailField(max_length=254)),
                ('storephone', models.CharField()),
                ('storetype', models.CharField()),
                ('storewebsite', models.CharField()),
                ('storelogo', models.ImageField(upload_to=profileseller.models.unique_filename)),
                ('storedescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SellerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_address', to='profileseller.address')),
                ('deliveryaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='profileseller.address')),
                ('pickupaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_address', to='profileseller.address')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_documents', to='profileseller.documents')),
                ('selleraddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_address', to='profileseller.selleraddress')),
                ('sellerprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to='profileseller.sellerprofile')),
            ],
        ),
    ]
