# Generated by Django 4.2.5 on 2023-12-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileseller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='remarks',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(default='Pending'),
        ),
    ]
