# Generated by Django 4.2.5 on 2024-02-24 05:16

from django.db import migrations, models
import django.db.models.deletion
import profileseller.models


class Migration(migrations.Migration):

    dependencies = [
        ('profileseller', '0003_seller_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='businessdocument',
        ),
        migrations.AlterField(
            model_name='documents',
            name='businessregdnumber',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='documents',
            name='ownername',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=profileseller.models.unique_filename)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessdocuments', to='profileseller.documents')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seller_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='profileseller.sellerprofile')),
            ],
        ),
    ]
