# Generated by Django 4.2.5 on 2024-03-07 06:51

from django.db import migrations, models
import profileseller.models


class Migration(migrations.Migration):

    dependencies = [
        ('profileseller', '0006_alter_documentimage_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='storelogo',
            field=models.ImageField(blank=True, null=True, upload_to=profileseller.models.unique_filename),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='storewebsite',
            field=models.CharField(blank=True, null=True),
        ),
    ]
