# Generated by Django 4.2.5 on 2024-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileseller', '0007_alter_sellerprofile_storelogo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='usertype',
            field=models.CharField(blank=True, null=True),
        ),
    ]
